[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "CageCavityCalc"
version = "1.0.5"

dependencies = [
    "numpy",
    "scipy",
    "scikit-learn",
    "rdkit"]

[project.scripts]
CageCavityCalc = "CageCavityCalc.__main__:main"
